---
title: "Materials"
format: html
---

## Week 1

*Readings*: 

- LDS1 [The Data Science Lifecycle](https://learningds.org/ch/01/lifecycle_intro.html) 
- LDS5 [Case Study: Why is my Bus Always Late?](https://learningds.org/ch/05/bus_intro.html)
- PDSH2.1 [Understanding data types in python](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)
- PDSH2.2 [The basics of numpy arrays](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)
- PDSH2.4 [Aggregations: min, max, and everything in between](https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html)

**Monday**: Course introduction [[slides](slides/week1-intro.qmd)]

**Lab sections**: Orientation to Jupyter notebooks [[html](labs/lab0-gettingstarted/lab0-gettingstarted.ipynb)]

**Wednesday**: Data science lifecycle [[slides](slides/week1-lifecycle.qmd)]

## Week 2

*Readings*:

- Wickham (2014). Tidy data. *Journal of statistical software* 59(10). [[link to paper](https://www.jstatsoft.org/article/view/v059i10)]
- PDSH3.1 [Introducing pandas objects](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)
- PDSH3.2 [Data indexing and selection](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html)
- PDSH3.7 [Merge and join](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html)
- PDSH3.8 [Aggregation and grouping](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html)

*Assignments*: 

* HW1, BRFSS case study, due Monday, October 16 [[html](hw/hw1-brfss/hw1-brfss.ipynb)]

**Monday**: Tidy data [[slides](slides/week2-tidy.qmd)]

**Lab sections**: Pandas [[html](labs/lab1-pandas/lab1-pandas.ipynb)]

**Wednesday**: Dataframe transformations [[slides](slides/week2-transform.qmd)]

## Week 3

*Readings*:

- LDS2.2 [Population, frame, sample](https://learningds.org/ch/02/data_scope_construct.html#)
- Van Buuren, Flexible Imputation of Missing Data, section 2.2 [Concepts in incomplete data](https://stefvanbuuren.name/fimd/sec-idconcepts.html)
- PDSH3.4 [Handling missing data](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)


*Assignments*:

- Mini project 1, due Monday, Oct 23 [[html](projects/mp1/mp1-airquality.ipynb)]

**Monday**: Sampling, bias, and missingness [[slides](slides/week3-sampling.qmd)]

**Lab sections**: Exploring sampling bias through simulation [[html](labs/lab2-sampling/lab2-sampling.ipynb)]

## Week 4

*Readings*:

- Wilke, [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/) Ch. 2-5 
- LDS11.1 [Choosing scale to reveal structure](https://learningds.org/ch/11/viz_scale.html)
- (Recommended) Cook, D., Lee, E. K., & Majumder, M. (2016). Data visualization and statistical graphics in big data analysis. Annual Review of Statistics and Its Application, 3, 133-159. [[link to paper](https://www.annualreviews.org/doi/full/10.1146/annurev-statistics-041715-033420)]
- (Recommended) Gelman, A., & Unwin, A. (2013). Infovis and statistical graphics: different goals, different looks. Journal of Computational and Graphical Statistics, 22(1), 2-28. [[link to paper](https://www.tandfonline.com/doi/full/10.1080/10618600.2012.761137)]
- (Recommended) Iliinsky, N. (2010). On beauty. Beautiful visualization: Looking at data through the eyes of experts, 1-13. [[link to chapter](http://mines.humanoriented.com/568/reading/bv_ch01.pdf)]

*Assignments*: 

- HW2, SEDA case study, due Monday, Oct 30 [[html](hw/hw2-seda/hw2-seda.ipynb)]

**Monday**: Statistical graphics [[slides](slides/week4-graphics.qmd)]

**Lab sections**: Data visualization [[html](labs/lab3-visualization/lab3-visualization.ipynb)]

**Wednesday**: Principles of figure design [[slides](slides/week4-principles.qmd)]


