---
title: "Miscellany"
format: html
---

## Reminders and suggestions

- Automated tests in assignment notebooks are a guide, not a confirmation or refutation of your answer. Don't rely too heavily on them, but do read the output message if they fail and think about what the message is telling you. On some occasions they will fail despite a correct answer; on others they will pass despite an incorrect answer. Furthermore, they will guide you to one particular strategy for obtaining the solution; most problems admit a few possible strategies.

- All assignments are due on Mondays. You get two free late assignments. Late submissions are due Wednesdays.

- Start your homeworks and mini-projects early.

- Take your own notes during class; don't simply rely on lecture slides.

## Troubleshooting

- If you need to recover the distribution copy of any assignment notebook, perhaps due to accidentally deleting cells or similar issues, simply rename the notebook containing your work on the LSIT server and then redeploy the notebook from the course website link.

- If you try to open a notebook and the server fails at the 'synchronizing git repository' stage, open the LSIT server separately, rename the `pstat100-content` directory, and then try opening the notebook from the website link again. If successfull, you will need to migrate all of your previous work into the new `pstat100-content` directory.